ipset wildcard match support (dnsmasq parity)
AdguardTeam/AdGuardHome pull request #2165
Opened 2020-10-07 11:28 UTC by dsheets

I started using the ipset functionality to grant restricted internet access to a smart projector and found that it did not behave as dnsmasq's ipset functionality. Specifically, `man dnsmasq` for `--ipset` states:

>  Domains and subdomains are matched in the same way as --address.

`man dnsmasq` for `--address` states:

> so --address=/example.com/ is equivalent to --server=/example.com/ and returns NXDOMAIN for example.com and all its subdomains.

and indeed we find at <http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=src/forward.c;hb=f60fea1fb0a288011f57a25dfb653b8f6f8b46b9#l588>:

```c
 591       /* Similar algorithm to search_servers. */
 592       struct ipsets *ipset_pos;
 593       unsigned int namelen = strlen(daemon->namebuff);
 594       unsigned int matchlen = 0;
 595       for (ipset_pos = daemon->ipsets; ipset_pos; ipset_pos = ipset_pos->next) 
 596         {
 597           unsigned int domainlen = strlen(ipset_pos->domain);
 598           char *matchstart = daemon->namebuff + namelen - domainlen;
 599           if (namelen >= domainlen && hostname_isequal(matchstart, ipset_pos->domain) &&
 600               (domainlen == 0 || namelen == domainlen || *(matchstart - 1) == '.' ) &&
 601               domainlen >= matchlen) 
 602             {
 603               matchlen = domainlen;
 604               sets = ipset_pos->sets;
 605             }
 606         }
```

Prior to this patchset, AGH was matching exactly and only the domain name passed in the ipset configuration setting and provided no way to specify the domain as a wildcard domain. One could argue that all topological operations should be available for this functionality (i.e. 'boundary domain', 'open set below domain', and 'closed set below domain') but dnsmasq does not offer that functionality and I do not require it for my deployment so it's out of scope.

In updating this behavior of `ipset`, I've refactored `dnsforward/ipset.go` slightly to make it easier to test by moving the side effects into a parameter function. I then expanded the tests and caught a segfault on some edge cases for DNS responses (missing question and/or answer sections... I'm not sure these arise in practice).

I have found some further issues that I have not included in this PR as I think they require a fundamental rethink of the way AGH interacts with ipsets. Specifically, invoking the `ipset` command is slow, the stderr is thrown away when an error occurs (and stdout which is logged is empty), there is no easy way to distinguish between IPv4 and IPv6 ipsets except for parsing `ipset list` (and this isn't done currently), so if you have both IPv4 and IPv6 ipsets, the logs will be full of error messages about bad `ipset add` invocations. Finally, because of the discarded stderr, when IPv4 `ipset add` commands occasionally fail, there is no way to know why.

Rather than trying to address these issues in the current design or doing the work myself before I submit it to you for review, I propose that AGH adopt https://github.com/ti-mo/netfilter and interface with a netlink kernel socket directly in pure go. I'm happy to reimplement the current `ipset add` functionality in terms of that library if you'd be willing to accept the new dependency.

Finally, please let me know if you'd like issues opened for any of the bugs or my dependency proposal. I am currently running this patchset and it is successfully keeping my projector from talking to anyone except NetFlix :-).

2020-10-08 11:58 UTC, ameshkov commented
Thank you for the pull request!

> Rather than trying to address these issues in the current design or doing the work myself before I submit it to you for review, I propose that AGH adopt https://github.com/ti-mo/netfilter and interface with a netlink kernel socket directly in pure go. 

Yeah, it makes perfect sense to me.

> I'm happy to reimplement the current ipset add functionality in terms of that library if you'd be willing to accept the new dependency.

We'll be happy to, thank you!

2020-11-23 09:53 UTC, ainar-g commented
<p>Hi,&#xA0;and&#xA0;thank you for&#xA0;your PR!&#x2003;I&#xA0;will try
to&#xA0;review it&#xA0;shortly.</p>

2020-11-23 10:25 UTC, ainar-g requested changes

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset.go
> +// Find the ipsets for a given host (accounting for subdomain wildcards)
It's better to start doc comments for unexported identifiers just like one would for exported, that is:

```go
// getIpsetNames finds the ipstes […]
```

That applies to the other doc comments below.

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset.go
> +	var found bool
Seems like a perfect place to use named returns, like we recommend in our recently-added `HACKING.md` file.

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset.go
> +		return
We're trying to switch away from the practice of logging errors at the error site and return a properly wrapped error instead.  So perhaps `addToIpset` should return an error.

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset.go
> +func (c *ipsetCtx) processMembers(ctx *dnsContext, addMember func(string, string, string)) int {
It's better to make the type of `addMember` a newtype.  And also document, at the site of the newtype's declaration, what the arguments are.

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset_test.go
> +func setup() {
We're trying to eschew global variables as much as possible.  Could you please rewrite the tests using the subtest feature instead?

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset_test.go
> +	return makeReq(fqdn, dns.TypeAAAA)
I don't think that adding another level of indirection makes any difference here.  If anything, I would say that it hurts readability.  Perhaps inline the body of `makeReq` here and above?

2020-11-23 10:25 UTC, ainar-g commented on dnsforward/ipset_test.go
> +	assert.Equal(t, resultDone, c.processMembers(ctx, addToBindings))
Again, I don't think this indirection is necessary or helpful.

2021-01-27 15:43 UTC, ainar-g commented
Sorry for the long response.  We'll probably go with #2179.  I'll try to review, improve, and merge it this week.

2021-01-27 15:43 UTC, closed without merging

2021-05-25 09:31 UTC, ihipop commented
seems to be merged at
 https://github.com/AdguardTeam/AdGuardHome/commit/510573a904e0fd184d6a2ccedf9ebe7b7ed81465
?