feat: add dns.ipset_file setting
AdguardTeam/AdGuardHome pull request #4686
Opened 2022-06-23 08:05 UTC by hellodword

just like the upstream_dns_file

2022-08-11 10:06 UTC, zhudan commented
watch!!

2022-09-06 14:40 UTC, ainar-g commented
Good day and apologies for the long wait.  It's generally better to propose a feature in an issue first, but since it's already done, can I ask, what is the problem you are trying to solve?  Is the ipset configuration really getting this large?

2022-09-06 15:58 UTC, hellodword commented
> Good day and apologies for the long wait. It's generally better to propose a feature in an issue first, but since it's already done, can I ask, what is the problem you are trying to solve? Is the ipset configuration really getting this large?

For example:

https://github.com/hezhijie0327/GFWList2AGH/tree/main/gfwlist2adguardhome

2022-09-08 01:52 UTC, hellodword commented
> I can see that these are lists of upstreams, correct? How is it related to ipsets?

For most usage in my country, `upstream_dns_file` protects our DNS, `ipset` define the whitelist or blacklist to pass through the firewall via VPN.

So the `ipset` often has simliar content and size with the `upstream_dns_file`.

2022-09-08 02:08 UTC, hellodword commented
For example:

`upstream_dns_file`:
```
https://doh.pub:443/dns-query
[/github.com/google.com/]tls://8.8.4.4
```

`ipset`:
```
ipset:
- github.com,google.com/ipset-for-vpn
```

2022-09-08 12:06 UTC, ainar-g commented
Hm, I see.  We'll review the change then.

2022-09-08 12:23 UTC, ainar-g requested changes
Please also:

1.  Merge the current `master` branch or rebase your branch on top of it, optionally with a squash.

2.  Describe the changes in `CHANGELOG.md`.

2022-09-08 12:23 UTC, ainar-g commented on internal/dnsforward/config.go
> +	IpsetListFileName string   `yaml:"ipset_file"`
Please add documentation.  Something like:

> IpsetListFileName, if set, points to the file with ipset configuration.  The format is the same as in IpsetList.

2022-09-08 12:23 UTC, ainar-g commented on internal/dnsforward/dnsforward.go
>  	}
This increases the [cyclomatic complexity][1] of method `Prepare` too much.  On `master`, we have finally reduced the complexity of all methods in package `dnsforward` to 10 and below.  Please put what is now on lines 484 to 501 to a separate method.  Do not forget about error context.

[1]: https://en.wikipedia.org/wiki/Cyclomatic_complexity

2022-09-12 13:51 UTC, merged

2022-09-12 13:54 UTC, ainar-g commented
Thanks for the contribution!