Add Globo Service
AdguardTeam/AdGuardHome pull request #4878
Opened 2022-08-30 15:11 UTC by eduardoaddad

Add Globoplay, Canais Globo, Premiere
Source for glbimg: https://s3.glbimg.com/v1/AUTH_c2986343db13479c82b8a9a301be7717/static/index.html

2022-08-30 16:11 UTC, ainar-g requested changes
@ameshkov, is this service in our current service index?  Should we add it there?

Also, do you approve adding this service to AGH?

2022-08-30 16:11 UTC, ainar-g commented on client/src/helpers/constants.js
> +
Please remove this empty line.

2022-08-30 16:11 UTC, ainar-g commented on internal/filtering/blocked.go
> +		"||api-soccer.globosat.tv^",
Please sort the rules.

Also, pay attention to the comment on `servicesData`.  `client/src/components/ui/Icons.js` must be updated as well.

2022-08-30 20:11 UTC, eduardoaddad commented on client/src/helpers/constants.js
> +
done

2022-08-30 20:58 UTC, eduardoaddad reviewed
.

2022-08-31 12:07 UTC, ainar-g requested changes
It seems like the merge has gone wrong, since `constants.js` seems removed.

2022-09-27 03:11 UTC, eduardoaddad commented
> It seems like the merge has gone wrong, since `constants.js` seems removed.

how can i restore this?

2022-09-29 02:26 UTC, eduardoaddad commented
> It seems like the merge has gone wrong, since `constants.js` seems removed.

Correct?

2022-10-06 13:24 UTC, ainar-g requested changes
See previous comments

2023-09-06 17:57 UTC, ainar-g commented
See https://github.com/AdguardTeam/AdGuardHome/issues/2604#issuecomment-1690454082.

2023-09-06 17:57 UTC, closed without merging