chore(i18n): improved the Simplified Chinese translation
AdguardTeam/AdGuardHome pull request #6223
Opened 2023-09-16 04:50 UTC by ttimochan

This Pull Request modifies some of the Simplified Chinese translation; and for visual effect, adds the necessary spaces where Chinese and English are mixed.

2023-09-17 11:38 UTC, cxw620 commented on client/src/__locales/zh-cn.json
>      "bootstrap_dns_desc": "DNS 服务器的 IP 地址，用于解析指定为上游的 DoH/DoT 解析器的 IP 地址。不允许评论。",
应该是 "不允许注释" 吧?

2023-09-17 11:48 UTC, ttimochan commented on client/src/__locales/zh-cn.json
>      "bootstrap_dns_desc": "DNS 服务器的 IP 地址，用于解析指定为上游的 DoH/DoT 解析器的 IP 地址。不允许评论。",
原翻译如此。OK，我会改进翻译。

2023-09-19 09:50 UTC, kLiHz requested changes

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "upstream_parallel": "使用并行的查询策略。同时查询所有上游服务器，Adguard Home 将会使用最快地上游服务器的查询结果",
```suggestion
    "upstream_parallel": "使用并行的查询策略。同时查询所有上游服务器，AdGuard Home 将会使用最快的上游服务器的查询结果",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "load_balancing_desc": "一次查询一台服务器。AdGuard Home 将使用加权随机算法来选择服务器，以便更常使用最快上游的服务器。",
```suggestion
    "load_balancing_desc": "一次查询一台服务器。AdGuard Home 将使用加权随机算法来选择服务器，以便更常使用最快的上游服务器。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "fallback_dns_placeholder": "每行输入一个备用 DNS 服务器",
```suggestion
    "fallback_dns_title": "后备 DNS 服务器",
    "fallback_dns_desc": "当上游 DNS 服务器没有响应时使用的后备 DNS 服务器列表。语法与上面的主要上游字段相同。",
    "fallback_dns_placeholder": "每行输入一个后备 DNS 服务器",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "dhcp_warning": "如果你想要启用内置的 DHCP 服务器，请确保在当前网络中没有其它起作用的 DHCP 服务器。否则，此操作可能会影响现有的网络设备！",
```suggestion
    "dhcp_warning": "如果你想要启用内置的 DHCP 服务器，请确保在当前网络中没有其它起作用的 DHCP 服务器。否则，此操作可能会中断已连接设备的网络连接！",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "dns_allowlists_desc": "在该 DNS 白名单的域名不会被拦截，即便是在 DNS 黑名单之中。",
```suggestion
    "dns_blocklists_desc": "AdGuard Home 将阻止匹配 DNS 黑名单中的域名",
    "dns_allowlists_desc": "在 DNS 白名单中的域名不会被拦截，即便它们出现在任意 DNS 黑名单中。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "example_meaning_filter_whitelist": "解除 example.org 及其所有子域名的拦截；",
```suggestion
    "example_meaning_filter_whitelist": "解除对 example.org 及其所有子域名的拦截；",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "example_upstream_doh3": "带有强制 <0>HTTP/3</0> 的加密 DNS-over-HTTPS，不会降级到 HTTP/2 或更低版本;",
```suggestion
    "example_upstream_doh3": "带有强制 <0>HTTP/3</0> 的加密 DNS-over-HTTPS，不会回退到 HTTP/2 或更低版本;",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "query_log_cleared": "查询日志已成功清空",
```suggestion
    "query_log_confirm_clear": "你确定想要清除全部查询日志吗？",
    "query_log_cleared": "查询日志已全部清除",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "query_log_clear": "清空查询日志",
```suggestion
    "query_log_clear": "清除查询日志",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "install_auth_desc": "您需要对 AdGuard Home 的网页管理界面配置密码认证。即使该 AdGuard Home 只能通过您的本地网络访问，也应该使用密码认证来避免 Adguard Home 被他人意外修改。",
```suggestion
    "install_auth_desc": "您需要对 AdGuard Home 的网页管理界面配置密码认证。即使该 AdGuard Home 只能通过您的本地网络访问，为它添加访问限制依旧十分重要。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "access_blocked_desc": "不要将此功能与过滤器混淆。AdGuard Home 将排除匹配这些域名的 DNS 查询，并且这些查询将不会在查询日志中显示。在此可以明确指定域名、通配符（wildcard）和网址过滤的规则，例如 \"example.org\"、\"*.example.org\" 或 \"||example.org^\"。",
```suggestion
    "access_blocked_desc": "不要将此功能与过滤器混淆。AdGuard Home 将排除匹配这些域的 DNS 查询，并且这些查询将不会在查询日志中显示。在此可以明确指定域名、通配符（wildcard）和网址过滤的规则，例如 \"example.org\"、\"*.example.org\" 或 \"||example.org^\"。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "statistics_clear_confirm": "您确定要清空统计数据？",
```suggestion
    "statistics_clear": " 清除统计数据",
    "statistics_clear_confirm": "您确定要清除全部统计数据？",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "statistics_cleared": "统计数据已成功清空",
```suggestion
    "statistics_cleared": "统计数据已全部清除",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "ignore_domains_title": "被忽略的域名",
```suggestion
    "ignore_domains_title": "被忽略的域",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "fastest_addr_desc": "查询所有 DNS 服务器并返回所有响应中速度最快的 IP 地址。因 AdGuard Home 必须等待全部 DNS 服务器响应，因而会降低 DNS 查询的速度，与此同时，此举将可能改善连接速度。",
```suggestion
    "fastest_addr_desc": "查询所有 DNS 服务器并返回所有响应中速度最快的 IP 地址。由于 AdGuard Home 必须等待全部 DNS 服务器响应，这会降低 DNS 查询的速度，但此举将会在总体上改善连接速度。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "tags_desc": "您可以选择与客户端对应的标记。标签可以包含在过滤规则中，并允许您更准确地使用它们。<0>了解更多</0>。",
```suggestion
    "tags_desc": "您可以选择与客户端对应的标记。标签可以包含在过滤规则中，并允许您更准确地应用它们。<0>了解更多</0>。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "disallow_this_client": "封禁这个客户端",
```suggestion
    "disallow_this_client": "不允许这个客户端",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
>      "client_blocked": "客户端 \"{{ip}}\" 被成功拦截",
```suggestion
    "client_blocked": "客户端 \"{{ip}}\" 被成功封禁",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
>      "client_unblocked": "成功解锁客户端 \"{{ip}}\"",
```suggestion
    "client_unblocked": "成功解除对客户端 \"{{ip}}\" 的封禁",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "cache_size_desc": "DNS 缓存大小（单位：字节）。如果要关闭缓存，请留空。",
```suggestion
    "cache_size_desc": "DNS 缓存大小（单位：字节）。若要关闭缓存，请留空。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "cache_optimistic_desc": "即使缓存中部分域名的结果已过期，也让 AdGuard Home 从缓存中响应，并尝试刷新它们。",
```suggestion
    "cache_optimistic_desc": "即使缓存中的结果已过期，也让 AdGuard Home 从缓存中响应，并尝试刷新它们。",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "clear_cache": "清空缓存",
```suggestion
    "confirm_dns_cache_clear": "您确定要清除 DNS 缓存吗？",
    "cache_cleared": "已成功清除全部 DNS 缓存",
    "clear_cache": "清除缓存",
```

2023-09-19 09:50 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "schedule_desc": "安排已拦截禁用的时间",
```suggestion
    "schedule_services": "配置暂停拦截服务的计划",
    "schedule_services_desc": "配置何时暂停 AdGuard Home 的拦截服务",
    "schedule_services_desc_client": "在一定时间内，停止拦截该客户端在 DNS 黑名单中的请求",
    "schedule_desc": "应用暂停拦截服务的时间段",
```

2023-09-19 10:04 UTC, ttimochan commented on client/src/__locales/zh-cn.json
> +    "fallback_dns_placeholder": "每行输入一个备用 DNS 服务器",
翻译成备用服务器更符合语境，不要过度机翻

2023-09-19 10:05 UTC, kLiHz commented
I suggest we ensure the consistency between translations of a certain term. For example we should make sure the word "block" in all similar context are translated the same way. Similarly, please mind the upper/lower cases of words. In this case we should keep the word "AdGuard" the same as what it appears in other places.

By the way, my changes may not be consistent or precise either. They just represents my opinion.

2023-09-19 10:09 UTC, ttimochan commented
> I suggest we ensure the consistency between translations of a certain term. For example we should make sure the word "block" in all similar context are translated the same way. Similarly, please mind the upper/lower cases of words. In this case we should keep the word "AdGuard" the same as what it appears in other places.


In the process of translation, I follow the principle of [信达雅](https://zh.wikipedia.org/zh-cn/%E4%BF%A1%E8%BE%BE%E9%9B%85), not machine translation, which is very important for users who use Simplified Chinese. If the user needs to see the original content, he can switch to English, but the translation into Simplified Chinese should be faithful and elegant!

2023-09-19 10:10 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "fallback_dns_placeholder": "每行输入一个备用 DNS 服务器",
I don't think this is machine translating. I think in Chinese "后备资源" appears more often than "备用资源". The word "后备" has a sense of "backup" and "support", while "备用" slightly lacks it.

2023-09-19 10:13 UTC, fernvenue commented
> I suggest we ensure the consistency between translations of a certain term. For example we should make sure the word "block" in all similar context are translated the same way.

Agree, that's a good example.

> Similarly, please mind the upper/lower cases of words. In this case we should keep the word "AdGuard" the same as what it appears in other places.

And yea, it should as same as English version all the time, use "AdGuard" not "Adguard".

2023-09-19 10:13 UTC, kLiHz commented
@ttimochan But please note that some of your changes didn't even met the principle of faithful. 😋 I usually check my translation several times  before I submitted them, and it would be nice if we can all do so.

2023-09-19 10:15 UTC, ttimochan commented
> @ttimochan But please note that some of your changes didn't even met the principle of faithful. 😋 I usually check my translation several times before I submitted them, and it would be nice if we all do so.

OK，I believe it should adhere to the Chinese context because certain terms may make perfect sense in an English context but could seem peculiar in a Chinese context.

2023-09-19 10:26 UTC, ttimochan commented
> > I believe it should adhere to the Chinese context because certain terms may make perfect sense in an English context but could seem peculiar in a Chinese context.
> 


You are right, I will revise the translated content again.

2023-09-19 11:06 UTC, ttimochan commented on client/src/__locales/zh-cn.json
> +    "upstream_parallel": "使用并行的查询策略。同时查询所有上游服务器，AdGuard Home 将会使用最快地上游服务器的查询结果",
Thanks.

2023-09-19 11:11 UTC, kLiHz commented on client/src/__locales/zh-cn.json
> +    "dns_blocklists_desc": "AdGuard Home 将阻止匹配 DNS 拦截清单的域名",
```suggestion
    "dns_blocklists_desc": "AdGuard Home 将阻止匹配 DNS 黑清单的域名",
```

The "blocklist" is translated as "黑名单" above. I think it's better to keep the consistency.

2023-09-19 11:13 UTC, ttimochan commented on client/src/__locales/zh-cn.json
> +    "dns_blocklists_desc": "AdGuard Home 将阻止匹配 DNS 拦截清单的域名",
OK.

2023-09-20 10:46 UTC, ainar-g commented
Thanks for the suggestions!  Our team will inspect them and they should land in the next release.

In the future, please try to access and use CrowdIn.  That is the one place AdGuard uses for all its internationalization work, and we really would not like to split the effort.

2023-09-20 10:46 UTC, closed without merging